POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json

{"email": "test2@email.com", "password": "testing123"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "manager", "password": "manager", "email": "manager@email.com"}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token ce043b6e68428560587f0d94d05c959d5e95148a


{}