# Generated by Django 4.2 on 2026-04-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
