export const courseData = [
  {
    id: 1,
    assigneeEmail: "john.doe@company.com",
    title: "Workplace Safety",
    description:
      "A project management course equips professionals with essential skills to plan, execute, and deliver results on time and within budget, ensuring teams stay aligned throughout the process.",
    progress: 38,
    numberOfLessons: 6,
    dateCreated: "2024-11-01",
    lessons: [
      {
        id: 1,
        title: "Introduction to safety",
        description: "An overview of core safety principles and why they matter in the workplace.",
        progress: 100,
        type: "Video",
        duration: "6 min",
      },
      {
        id: 2,
        title: "Hazard types",
        description: "Identifying and categorising physical, chemical, and biological hazards.",
        progress: 100,
        type: "Video",
        duration: "5 min",
      },
      {
        id: 3,
        title: "Emergency procedures",
        description: "Step-by-step guidance on what to do in the event of a workplace emergency.",
        progress: 50,
        type: "Video",
        duration: "8 min",
      },
      {
        id: 4,
        title: "PPE guidelines",
        description: "How to select, use, and maintain personal protective equipment correctly.",
        progress: 0,
        type: "Video",
        duration: "7 min",
      },
      {
        id: 5,
        title: "Reporting incidents",
        description: "The correct process for logging and escalating workplace incidents.",
        progress: 0,
        type: "Article",
        duration: "9 min",
      },
      {
        id: 6,
        title: "Review & summary",
        description: "A final recap of everything covered in the course.",
        progress: 0,
        type: "Article",
        duration: "10 min",
      },
    ],
  },
  {
    id: 2,
    assigneeEmail: "john.doe@company.com",
    title: "Fire Safety Awareness",
    description:
      "This course covers fire prevention, emergency evacuation procedures, and the correct use of fire fighting equipment to keep employees safe.",
    progress: 100,
    numberOfLessons: 4,
    dateCreated: "2024-09-15",
    lessons: [
      {
        id: 1,
        title: "Fire prevention basics",
        description: "Common causes of workplace fires and how to prevent them.",
        progress: 100,
        type: "Video",
        duration: "5 min",
      },
      {
        id: 2,
        title: "Evacuation procedures",
        description: "How to safely evacuate a building during a fire emergency.",
        progress: 100,
        type: "Video",
        duration: "6 min",
      },
      {
        id: 3,
        title: "Using a fire extinguisher",
        description: "The PASS technique and which extinguisher to use for different fire types.",
        progress: 100,
        type: "Video",
        duration: "4 min",
      },
      {
        id: 4,
        title: "Fire warden responsibilities",
        description: "Roles and duties of a designated fire warden in the workplace.",
        progress: 100,
        type: "Article",
        duration: "7 min",
      },
    ],
  },
  {
    id: 3,
    assigneeEmail: "john.doe@company.com",
    title: "Data Protection & GDPR",
    description:
      "Understand your obligations under GDPR, how to handle personal data responsibly, and what to do in the event of a data breach.",
    progress: 60,
    numberOfLessons: 5,
    dateCreated: "2025-01-10",
    lessons: [
      {
        id: 1,
        title: "What is GDPR?",
        description: "An introduction to the General Data Protection Regulation and who it applies to.",
        progress: 100,
        type: "Article",
        duration: "8 min",
      },
      {
        id: 2,
        title: "Lawful basis for processing",
        description: "The six lawful bases for processing personal data and when to use each.",
        progress: 100,
        type: "Article",
        duration: "7 min",
      },
      {
        id: 3,
        title: "Data subject rights",
        description: "Understanding the rights individuals have over their personal data.",
        progress: 100,
        type: "Video",
        duration: "9 min",
      },
      {
        id: 4,
        title: "Handling a data breach",
        description: "Steps to take when a data breach occurs and reporting obligations.",
        progress: 50,
        type: "Video",
        duration: "6 min",
      },
      {
        id: 5,
        title: "GDPR assessment",
        description: "Test your knowledge of GDPR principles and responsibilities.",
        progress: 0,
        type: "Article",
        duration: "10 min",
      },
    ],
  },
  {
    id: 4,
    assigneeEmail: "john.doe@company.com",
    title: "Mental Health in the Workplace",
    description:
      "Explore how to recognise signs of poor mental health, support colleagues effectively, and build a culture of psychological safety at work.",
    progress: 0,
    numberOfLessons: 5,
    dateCreated: "2025-03-20",
    lessons: [
      {
        id: 1,
        title: "Understanding mental health",
        description: "What mental health means and why it matters in a professional setting.",
        progress: 0,
        type: "Video",
        duration: "7 min",
      },
      {
        id: 2,
        title: "Recognising the signs",
        description: "Behavioural and emotional indicators that a colleague may be struggling.",
        progress: 0,
        type: "Article",
        duration: "6 min",
      },
      {
        id: 3,
        title: "Having supportive conversations",
        description: "How to approach a sensitive conversation with empathy and without judgement.",
        progress: 0,
        type: "Video",
        duration: "8 min",
      },
      {
        id: 4,
        title: "Stress and burnout",
        description: "The difference between stress and burnout, and strategies to manage both.",
        progress: 0,
        type: "Video",
        duration: "9 min",
      },
      {
        id: 5,
        title: "Building a healthy team culture",
        description: "Practical steps managers and employees can take to promote wellbeing.",
        progress: 0,
        type: "Article",
        duration: "5 min",
      },
    ],
  },
];