name: Sync to Vercel Repo

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Push to Vercel Repo
        env:
          TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git remote add vercel https://x-access-token:${TOKEN}@github.com/its-jedu/lms-bootcamp-project.git

          git push vercel main --force